# Generated by Django 4.2.7 on 2023-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='resumen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
